title: Stackbit Ampersand Theme
baseURL: /
params:
  description: Medium inspired blogging theme for Stackbit
  layout_style: grid
  palette: green
  header:
    type: header
    template: header
    title: Ampersand
    logo_img: images/logo.png
    has_nav: true
    nav_links:
      - type: action
        template: action
        label: Home
        url: /
        style: link
      - type: action
        template: action
        label: About
        url: /about
        style: link
      - type: action
        template: action
        label: Style Guide
        url: /style-guide
        style: link
      - type: action
        template: action
        label: Contact
        url: /contact
        style: link
  footer:
    type: footer
    template: footer
    content: >-
      &copy; Stackbit. All rights reserved. This Jamstack site was created on <a
      href="https://www.stackbit.com" target="_blank"
      rel="noopener">Stackbit</a>. Get yours <a
      href="https://app.stackbit.com/create?theme=ampersand" target="_blank"
      rel="noopener">here</a>.
    has_social: true
    social_links:
      - type: action
        template: action
        label: Twitter
        url: 'https://twitter.com/'
        style: icon
        icon_class: fa-twitter
        new_window: true
      - type: action
        template: action
        label: Instagram
        url: 'https://www.instagram.com/'
        style: icon
        icon_class: fa-instagram
        new_window: true
      - type: action
        template: action
        label: GitHub
        url: 'https://github.com/'
        style: icon
        icon_class: fa-github
        new_window: true
      - type: action
        template: action
        label: LinkedIn
        url: 'https://www.linkedin.com/'
        style: icon
        icon_class: fa-linkedin
        new_window: true
      - type: action
        template: action
        label: DEV
        url: 'https://dev.to/'
        style: icon
        icon_class: fa-dev
        new_window: true
    has_subscribe: true
    subscribe_title: Subscribe for new updates
    subscribe_content: >-
      Subscribe to my email newsletter to receive useful articles and special
      offers. This monthly email is sent out on the first of every month.
    subscribe_action: /subscribe-success
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
